version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Europe/Berlin'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Europe/Berlin'
