indent_style                 = "Block"
newline_style                = "Unix"
max_width                    = 80
tab_spaces                   = 2
error_on_line_overflow       = true
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true
format_strings               = true
group_imports                = "StdExternalCrate"
imports_granularity          = "Crate"
reorder_imports              = true
wrap_comments                = true
