name: 🧪 Test and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup rust
      run: |
        rustup update --no-self-update stable
        rustup component add --toolchain stable rustfmt rust-src clippy
        rustup default stable

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
      with:
        key: stable

    - name: Lint code
      run: cargo clippy

    - name: Run unit tests
      run: cargo test --bins

    - name: Run integration tests
      run: cargo test --test '*'

    - name: Build release
      run: cargo build --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: git-squad
        path: target/release/git-squad
        retention-days: 7
